# Generated by Django 2.0.4 on 2018-04-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='perfer',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='senstive',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
